"""
所有提示词模板 — 向后兼容层

从 core.prompts.rag 重新导出，保持 api/ 层的向后兼容性。
新代码应直接导入 core.prompts.rag。
"""

from core.prompts.rag import (
    RAG_SYSTEM_PROMPT,
    RAG_TEMPLATE,
    SIMPLE_CHAT_SYSTEM_PROMPT,
    DEEP_RESEARCH_FIRST_ITERATION_PROMPT,
    DEEP_RESEARCH_FINAL_ITERATION_PROMPT,
    DEEP_RESEARCH_INTERMEDIATE_ITERATION_PROMPT,
)

__all__ = [
    "RAG_SYSTEM_PROMPT",
    "RAG_TEMPLATE",
    "SIMPLE_CHAT_SYSTEM_PROMPT",
    "DEEP_RESEARCH_FIRST_ITERATION_PROMPT",
    "DEEP_RESEARCH_FINAL_ITERATION_PROMPT",
    "DEEP_RESEARCH_INTERMEDIATE_ITERATION_PROMPT",
]
